### ISSUE TITLE
More go-to buttons

### ISSUE THREAD

**Issue by Nimuedaertya** [Nimuedaertya/reallife-quest-murder-game#20]
Player Overview => Start Page AND Task Overview
Task Overview => Start Page AND Player Overview
Start Page => Player Overview AND Task Overview

**Comment by CyberDev01** [comment]
Tested with Browsers: Firefox, Brave
Tested on: Smartphone (Android 14, Google Pixel), Laptop (Ubuntu 22.04-Derivative)

Buttons "Player Overview" and "Task Overview" is not shown on Start-Page.

Maybe because the entered username is not saved, because the Task-Overview probably needs a state or username to work with?
